export const ActionTypes = {
  ADD_POINT: 'ADD_POINT',
  REMOVE_POINT: 'REMOVE_POINT',
  SWAP_SIDES: 'SWAP_SIDES',
  RESET_SCORES: 'RESET_SCORES',
  TOGGLE_TIMER: 'TOGGLE_TIMER',
  RESET_TIMER: 'RESET_TIMER',
  SET_TIME: 'SET_TIME',
  SET_TEAM_NAME: 'SET_TEAM_NAME',
  RESET_MATCH: 'RESET_MATCH',
  SET_SETTINGS_MODAL_VISIBLE: 'SET_SETTINGS_MODAL_VISIBLE',
  SET_SETS_TO_WIN: 'SET_SETS_TO_WIN',
  DECREMENT_TIMEOUT: 'DECREMENT_TIMEOUT',
  LOAD_STATE: 'LOAD_STATE',
  SET_TEAM_ROTATION: 'SET_TEAM_ROTATION',
  SET_TEAM_COLOR: 'SET_TEAM_COLOR',
  TOGGLE_SERVE: 'TOGGLE_SERVE',
};

